version: "3.8"

services:

  php:
    container_name: php-app
    build: .
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    ports:
      - 9001:80
    
  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '50612596'
      MYSQL_DATABASE: db_app
      MYSQL_USER: admin_sql
      MYSQL_PASSWORD: root@123
    ports:
      - "3307:3306"
